REST APIs for Snippets Plugin
mantisbt-plugins/Snippets pull request #66
Opened 2023-08-27 02:32 UTC by vboctor

Implemented APIs for:

- Add Snippet
- Delete Snippet
- Update Snippet
- Search Snippets

I updated the web UI to use the add command, but didn't do the rest. The core APIs are not great.

2023-08-28 15:51 UTC, dregad requested changes

2023-08-28 15:51 UTC, dregad commented on Snippets.php
>  				$t_app->delete( '/snippets/{snippet_id}', [ $t_plugin, 'snippet_delete' ] );
Follow naming convention for route methods (prefix `route_`)

2023-08-28 15:51 UTC, dregad commented on core/commands/SnippetGetCommand.php
> +		# global is always false, because we will expicitly include the global user id (NO_USER)
Typo *explicitly*

2023-08-28 15:51 UTC, dregad commented on core/commands/SnippetDeleteCommand.php
> +	}
Missing return

2023-08-28 15:51 UTC, dregad commented on core/commands/SnippetGetCommand.php
> +		$t_snippets = Snippet::load_by_type_user( 0, $this->owner_id, /* global */ false );
I'm not sure what use case you had in mind for this endpoint, but it does not do what I expected.

Calling the API endpoint `GET /plugins/Snippets/snippet/` with a token for user X, I thought it would return the list of all snippets available to X (i.e. private + global). Instead it returns only the private snippets, so if X doesn't have any, I get an empty list which is confusing.

I think a query parameter should allow to select _private_, _global_ or _both_, with default to both, this way all scenarios can be covered by a single API call.

2023-08-28 15:51 UTC, dregad commented on core/commands/SnippetGetCommand.php
> +				access_denied();
Global snippets are effectively readable publicly, why deny access to them ?

2023-08-28 15:54 UTC, dregad commented on core/commands/SnippetGetCommand.php
> +				access_denied();
Nevermind,

2023-08-28 16:07 UTC, dregad commented on core/commands/SnippetDeleteCommand.php
> +			# TODO: ideally we should have a generic ENTITY_NOT_FOUND error to trigger 404 http status code
Makes sense.

This requires a change in MantisBT Core (new constant, message + handling in mc_api.php ApiObjectFactory::faultFromException(), so you should open an issue at https://mantisbt.org/bugs to track it.

2023-08-29 23:41 UTC, vboctor commented on Snippets.php
> +				$t_app->get( '/snippets/search', [ $t_plugin, 'search' ] );
Within each plugin it is useful to have a namespace per entity. This potentially allows more entities later. For example, `completions` for auto-completions, etc. It is also consistent with core API where you have entities under the endpoint.

2023-08-29 23:44 UTC, vboctor commented on Snippets.php
> +		require_once( dirname( __FILE__ ) . '/core/commands/SnippetSearchCommand.php' );
For the sub-directory, I'm just again following what we have in core.

I'll look into not specifying the path for each one.

2023-08-30 02:54 UTC, vboctor commented on core/Snippets.API.php
> +			return empty( $snippets ) ? null : $snippets[$id];
I'm not sure how you got the errors or you are just predicting it will happen?  I have to say the implementation of the plugin is not hardened for the non-happy cases in general. It is assumed that requests are generally valid. i.e. if you are retrieving an ID it exists and it is mostly driven by UI.

Note that this API is designed for two use cases:
- An int is provided and in this case it returns a single object, not an array. Hence, the caller won't be calling count and if it does it will fail in the success and failure cases.
- An array of int is provided in this it will always return an array and it will always be able to call count() on it.

I clarified in the phpdoc of the method.

2023-08-30 02:57 UTC, vboctor commented on core/commands/SnippetDeleteCommand.php
> +			# TODO: ideally we should have a generic ENTITY_NOT_FOUND error to trigger 404 http status code
I was planning to. Here it is:
https://www.mantisbt.org/bugs/view.php?id=32892

2023-08-30 02:59 UTC, vboctor commented on core/commands/SnippetDeleteCommand.php
> +	}
Not a missing return since delete command return no content, but it is wrong phpdoc. Fixed the phpdoc.

2023-08-30 03:08 UTC, vboctor commented on core/commands/SnippetGetCommand.php
> +		$t_snippets = Snippet::load_by_type_user( 0, $this->owner_id, /* global */ false );
There are two APIs to retrieving snippets:

- Search API - can have a query (filter string) or empty. It looks at both private / global snippets. So this gets all the matching snippets accessible to the user.

- Get API - can query either global or private, but not both. It is designed mainly for the equivalent of Global Snippets lists and My Snippets list for managing the snippets.

The internal APIs are not great in reflecting the intent of their usage. But I can document this clearly in the phpdoc of each of the two APIs.

2023-08-30 03:12 UTC, vboctor commented on core/Snippets.API.php
> +			return empty( $snippets ) ? null : $snippets[$id];
I have updated the documentation for the Get API to clarify the user cases vs. the Search API.

2023-08-30 03:13 UTC, vboctor commented
@dregad I addressed your comments. Please have another look.

2023-08-30 15:52 UTC, dregad commented on Snippets.php
> +				$t_app->get( '/snippets/search', [ $t_plugin, 'search' ] );
I hear the argument, and it would definitely make sense in a more complex plugin that handles several entities (e.g. source integration), but here it really feels like adding unnecessary complexity.

2023-08-30 15:55 UTC, dregad commented on core/Snippets.API.php
> +			return empty( $snippets ) ? null : $snippets[$id];
> I'm not sure how you got the errors or you are just predicting it will happen?

I did not actually (try to) trigger the errors from within the plugin. This was actually flagged by static analysis - you can't do `foreach( null ... )` or `count( null )` and with the direction PHP is taking towards stricter type checking, it will likely end up as an error instead of a warning in the future so we might as well initialize the variable in a way that does not trigger any warning now, i.e.
```php
return empty( $snippets ) ? [] : $snippets[$id];
```

Thanks for updating the documentation, it is clear now.

2023-08-30 15:55 UTC, dregad commented on Snippets.php
> +		require_once( dirname( __FILE__ ) . '/core/commands/SnippetSearchCommand.php' );
Let's keep things in perspective... MantisBT core has dozens of API files and classes, so it's mandatory to have some structure. For a simple plugin like this and just 5 files, there is no added value for a subdirectory.

2023-08-30 15:55 UTC, dregad commented on Snippets.php
>  				$t_app->delete( '/snippets/{snippet_id}', [ $t_plugin, 'snippet_delete' ] );
This was not addressed

2023-08-30 15:57 UTC, dregad commented on core/commands/SnippetDeleteCommand.php
> +	}
The method's signature should be consistent with the parent class's Command::process(), which is declared to return an array (not void).

https://github.com/mantisbt/mantisbt/blob/33ef34f8d531ccf0731e25499ad3986a92047a28/core/commands/Command.php#L59-L65

2023-08-30 15:57 UTC, dregad commented on core/commands/SnippetGetCommand.php
> +		$t_snippets = Snippet::load_by_type_user( 0, $this->owner_id, /* global */ false );
Ah so it was just a misunderstanding on my end then. Thanks for clarification and updating the doc.

2023-09-06 05:54 UTC, merged